- .circleci/config.yml
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/3)
> Add: dev site trigger

- api.md
- client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/5)
> add a header for dev site

- api.md
add header instruction for api.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/6)
> Update api doc

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/10)
> add branch build config for setting branch rules in github

- .travis.yml
- client.go
- contract.go
- types/option.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/12)
> Add epoch option for contract call and get next nonce

- README.md
- api.md
- client.go
- contract.go
- example/example_client/main.go
- interface.go
- types/wrapped_error.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/15)
> Support client with retry and add example for client

- client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/18)
> fix bug for batch call methods when input length is 0

- example/context/config.toml
- types/types.go
- types/types_test.go
add method for getting address type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/22)
> Dev get address type

- account.go
- types/types.go
- utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/24)
> import account by private key

- account.go
- utils/crypto.go
- utils/crypto_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/26)
> add function for exporting private key

- account.go
- types/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/27)
> new account compatible with eth

- account.go
- example/context/config.toml
- example/example_account_manager/main.go
- example/example_contract/main.go
- go.mod
- types/types.go
- types/types_test.go
- utils/crypto_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/28)
> support checksum for account

- client.go
- example/context/config.toml
- types/deposit_info.go
- types/transaction.go
- types/vote_stake_info.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/31)
> update for rpc

- api.md
- changeLog.md
- client.go
- constants/constants.go
- contract_meta/internal_contract/.godocdown.markdown
- contract_meta/internal_contract/admin_control.go
- contract_meta/internal_contract/sponsor_whitelist_control.go
- contract_meta/internal_contract/staking.go
- example/context/config.toml
- example/context/prepare.go
- example/context/utils.go
- example/example_client/main.go
- example/example_internal_contract/admin.go
- example/example_internal_contract/main.go
- example/example_internal_contract/sponsor.go
- example/example_internal_contract/staking.go
- generate_doc.sh
- types/rpc.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/35)
> support interneal contract

- types/transaction.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/39)
> change tx receipt txExecErrorMsg type be pointer

- rpc/http.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/40)
> fix amount of TIME_WAIT when concurrency request

- interface.go
- types/epoch.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/44)
> enhance to support infura

- changeLog.md
- client.go
- example/example_client/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/43)
> fix sbuscribLogs

- contract.go
- interface.go
- interface_mock.go
- types/block.go
- types/epoch.go
- types/log.go
- types/option.go
- types/trace.go
- types/transaction.go
- types/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/47)
> Some enhancements for RPC proxy

- account.go
- client.go
- contract.go
- go.mod
- types/transaction_signed.go
- types/transaction_unsigned.go
- types/types.go
- types/wrapped_error.go
- utils/crypto.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/48)
> refactor errors with standard lib

- types/cfxaddress/address.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/52)
> Add prefix for get base32 address methods for extension

- client.go
- example/context/config.toml
- example/example_client/main.go
- interface.go
- types/cfxaddress/address.go
- types/cfxaddress/network_type.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/56)
> Add function for new cfx address conveniently

- rpc/json.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/57)
> Support to handle json error in RPC framework

- types/block.go
- types/block_test.go
- types/cfxaddress/address.go
- types/cfxaddress/address_test.go
- types/log.go
- types/log_test.go
- types/transaction.go
- types/transaction_test.go
Unittests are also added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/79)
> RLP encoding/decoding support for types like block/transaction/log etc.,

- types/log.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/104)
> Add FromBlock/ToBlock field in types.LogFilter

- types/log.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/105)
> Bugfix unmarshalling Offset filed of types.LogFilter is missing.

- client.go
- interface.go
- utils/crypto.go
- utils/crypto_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/134)
> cache chainID in client

- client.go
- contract.go
- utils/abiutil/decoder.go
- utils/abiutil/decoder_test.go
- utils/addressutil/addressutil.go
- utils/rpc_error.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/135)
> Decode rpc error in Client.Call

- cfxclient/bulk/bulk_test.go
- changeLog.md
- client.go
- go.mod
- go.sum
- utils/abiutil/decoder.go
- utils/abiutil/decoder_test.go
- utils/rpc_error.go
- utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/136)
> decode rpc error in Client.BatchCall

- types/cfxaddress/address.go
- types/cfxaddress/address_type.go
- types/cfxaddress/address_type_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/140)
> return unknown type for address start without '0x0,0x8,0x1'

- client.go
- interface.go
- types/pos/pos.go
- types/transaction_signed.go
- utils/crypto.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/141)
> forbid address to in unkown type when send transaction

- types/trace.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/145)
> define SpaceType

- types/pos/pos.go
fix #139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/146)
> update field Block.PivotDecision type

- types/cfxaddress/address.go
- types/cfxaddress/address_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/150)
> add method for shorten address

- types/cfxaddress/address.go
- types/cfxaddress/address_test.go
fix #156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/157)
> return correct networkId at method cfxaddress tocommon

- README.md
- SUMMARY.md
- changeLog.md
- docs/getting_started/interacting_with_node.md
- docs/quickstart.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/159)
> Optimize gitbook

- rpc/http.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/161)
> Add http request in RPC context for extention

- account.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/163)
> replace map by sync.map

- contract_meta/standard_contract/erc1155.go
- contract_meta/standard_contract/erc20.go
- contract_meta/standard_contract/erc721.go
- contract_meta/standard_contract/erc777.go
- go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/165)
> Standard contracts

- cmd/cfxabigen/main.go
- docs/cfxabigen.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/166)
> update cfxabigen description

- types/rpc.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/167)
> add field TotalEspaceTokens in TokenSupplyInfo

- go.mod
- go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/168)
> downgrade go-ethereum version to v1.10.15

- client_retry.go
- go.mod
- go.sum
- utils/rpc_error.go
- utils/utils.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/169)
> remove utils.IsRPCJSONError

- go.mod
- go.sum
- integration_test/client_cfx_test.go
- types/epoch.go
- types/epoch_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/172)
> add latest_finalized to epoch tags

- client.go
- integration_test/client_cfx_test.go
- interface.go
- types/rpc.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/175)
> fix rpc GetPoSRewardByEpoch

- cfxclient/bulk/bulk_test.go
- client.go
- go.mod
- go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/176)
> support setting max connection number for client with http(s) protocal

- interface.go
账号管理中 私钥的导入和导出方法 支持调用
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/178)
> support ImportKey and Export interface

- client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/180)
> not set gasprice when estimate

- client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/183)
> get networkid when new client

- client.go
- client_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/186)
> fix crash when Close client

- .gitignore
- client.go
- client_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/188)
> always set gasprice to nil when EstimateGasAndCollateral

- types/log.go
- types/log_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/189)
> remove offset&limit from LogFilter

- cfxclient/bulk/bulk_caller_cfx.go
- client.go
- types/pos/pos.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/193)
> support cfx_getParamsFromVote

- cfxclient/bulk/bulk_test.go
- contract_meta/internal_contract/abi_test.go
- contract_meta/internal_contract/cross_space_call.go
- contract_meta/internal_contract/params_control.go
- contract_meta/internal_contract/pos_register.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/195)
> Internal contract2

- client_test.go
- types/pos/pos.go
- types/pos/transaction_payload.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/go-conflux-sdk/199)
> fix pos GetTransactionByNumber return

- client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/200)
> dont clear gasPrice when estimate

- types/enums/TransactionOutCome.go
- types/transaction.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/206)
> add method for calc transaction outcome type

- cfxclient/bulk/bulk_caller_debug.go
- client_trace.go
- interface.go
- types/epoch.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/207)
> Tidy interface

- types/pos/bls.go
- types/pos/pos.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/208)
> Supports BCS serde for pos ledger

- .github/workflows/go.yml
- .travis.yml
- go.mod
- go.sum
- light/bcs/bcs.go
- light/bcs/encode.go
- light/bcs/encode_test.go
- light/bcs/map.go
- light/bcs/map_test.go
- light/contract/LightNode.abi
- light/contract/LightNode.go
- light/contract/Provable.abi
- light/contract/Provable.go
- light/contract/convert.go
- light/contract/encode.go
- light/mpt.go
- light/mpt/key.go
- light/mpt/nibble_path.go
- light/mpt/nibble_path_test.go
- light/mpt/node.go
- light/mpt/proof.go
- light/mpt/proof_test.go
- light/primitives/bool.go
- light/primitives/receipt.go
- light/proof.go
- light/readme.md
- light/relay.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/210)
> Supports light node contract

- light/contract/convert.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/211)
> relay pos ledger in order

- light/relay.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/212)
> Fix issues when relay blocks for light node

- types/transaction.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/213)
> add type for pending reason

- light/contract/LightNode.abi
- light/contract/LightNode.go
- light/contract/encode.go
- light/proof.go
- light/readme.md
- light/relay.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/214)
> Light relay sparsely

- light/proof.go
- light/relay.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/215)
> fix relay issue

- types/pos/bls.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/218)
> optimize bls verification for pos block

- light/contract/LedgerInfo.abi
- light/contract/LedgerInfo.go
- light/contract/LightNode.abi
- light/contract/LightNode.go
- light/contract/convert.go
- light/relay.go
- types/pos/bls.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/219)
> Supports to validate BLS signatures on chain

- light/contract/LedgerInfo.abi
- light/contract/LedgerInfo.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/220)
> Update light node contract abi

- changeLog.md
- integration_test/client_cfx_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/223)
> Gnore test get sponsor info

- contract_meta/internal_contract/sponsor_whitelist_control.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/226)
> support getAvailableStoragePoints

- client.go
- go.mod
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/228)
> client support WithContext for attach context on calling rpc

- client_pos.go
- interface.go
- types/pos/pos_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/229)
> fix pos rpc about variadic parameters

- account.go
- go.sum
- interface.go
- privatekey_am.go
- privatekey_am_test.go
- types/errors/errors.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/238)
> Merge provider sign

- types/transaction_signed.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/go-conflux-sdk/241)
> add lenth judge for decoding SignedTransaction
